### ISSUE TITLE
Баг, связанный с RSS

### ISSUE THREAD

**Issue by 1024--** [wiistriker/govnokod.ru#31]
В [своём посте](http://govnokod.ru/18246) **Dev_18** упомянул баг: если запостить код в описание, с RSS выйдет питушня.

Например, для его [поста 18246](http://govnokod.ru/18246) можно открыть http://govnokod.ru/comments/18178/rss и увидеть следующее:

```
http://govnokod.ru/comments/18245/rss ru support@govnokod.ru (govnokod.ru support) Mzz.Framework v.100500-release Thu, 28 May 2015 00:15:19 +0400 Fatal error: Call to a member function getCreated() on a non-object in /home/striker/applications/govnokod/tmp/templates_c/1563503196.file.export_quote_rss.tpl.php-ru.php on line 21
```

**Comment by 1024--** [comment]
**inkanus-gray** [написал](http://govnokod.ru/18246#comment287574): _Там ноль комментариев. Пышечка возвращает не пустой массив, а null, false, 0 или ещё какое-нибудь безумное значение, если не удалось загрузить данные._

**Comment by wiistriker** [comment]
RSS еще кто-то читает?

**Comment by 1024--** [comment]
> RSS еще кто-то читает?

Dev_18, видимо, читает
