### ISSUE TITLE
Вас там школьники ддосят

### ISSUE THREAD

**Issue by j123123** [wiistriker/govnokod.ru#34]
Школьник @catnikita255 забаттхертил оттого, что его недоОС начали обсирать на говнокоде, и решил заDDoSить сайт со своими друзьями-школьниками. Для исправления этого бага, предлагаю перенаправить DNS говнокода на айпи сайта с его говноОС, или например мамке его нажаловаться, чтоб она дала ремнем по его и без того раскочегаренной сраке
![Trollface](https://lurkmore.so/images/2/2d/Trollface_HD.png)

**Comment by catnikita255** [comment]
Лол, не сможешь. А дудос давно кончился.

**Comment by j123123** [comment]
Не смогу чего? Не смогу тебе навредить? Вообще-то смогу, только я пока не буду раскрывать свои планы.

**Comment by 1024--** [comment]
А в 2017м ботов понавелось. Капчу **сами** разгадывают, пишут какую-то хрень вида <случайная строка> <HTML ссылки>:
`wh0cd70292 <a href=http://buycafergot.us.com/>buy cafergot</a> <a href=http://propecia3.us/>propecia hair loss</a>`
Помогите! Сток совсем засрали.

**Comment by wiistriker** [comment]
Ща разберемся

**Comment by 1024--** [comment]
Рекламные боты всё ещё спамят :(
Кактус 6 марта обрисовал ситуацию в [этом](http://govnokod.ru/22491#comment373912) и [этом](http://govnokod.ru/22491#comment373913) комментариях, а также предложил способы борьбы:

> Есть идеи, как защититься от спама:
> 1. Не показывать форму ввода комментария гостю, если он пришёл без cookies или если отсутствует Referer.
> 2. Вообще не показывать гостям форму ввода комментария в голом HTML, создавать её по клику. > Сайт будет неюзабелен без JS, но сейчас это уже мало кого волнует.
> 
> Есть шанс, что придёт бот, поддерживающий JS, cookies, Referer, но от тупых ботов это уже хоть какая-то защита.

**Comment by wiistriker** [comment]
Так, часть почистил. Гостям пока запрещено постить комменты

**Comment by 1024--** [comment]
3 минуты назад бот пробил усложнённую капчу: http://govnokod.ru/17518#comment377818

**Comment by 1024--** [comment]
Тут [попросили](http://govnokod.ru/21792#comment378910) передать об эротических комментариях.
Иногда ради этого создают целые посты с общих учёток:
http://govnokod.ru/22626
http://govnokod.ru/22625
http://govnokod.ru/22624
http://govnokod.ru/22623
Иногда спамят в уже существующих постах:
http://govnokod.ru/21874#comment378496
Кто-то хочет, чтобы аккаунт bagor удалили, хотя с него раньше писали здравомыслящие анонимусы.

**Comment by 1024--** [comment]
О великий Страйкер, жители Говнокодика взывают к Тебе. В стоке возятся чумные гости и загрязняют его, посты заминусованы, и на главной ничего нового нет.

Вот теперь как выглядит ГК: http://govnokod.ru/22916

**Comment by wiistriker** [comment]
Гостя отрубил, вставил дополнительные проверки при комментировании/выставлении рейтинга, мусор частично подчистил

**Comment by 1024--** [comment]
Dear wiistriker,

The email sent to ivan009@zell.tk with subject
"Re: [wiistriker/govnokod.ru] Вас"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to ivan009@zell.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by wiistriker** [comment]
@1024--, что это?

**Comment by 1024--** [comment]
(оффтоп) прошу прощения, перенаправил поток почты через временную фигню на TK Mailias, а оно бомбануло автоматическими ответами

**Comment by ghost** [comment]
Вы если сайт открываете то сделайте качественно на века, и тонких тролей побольше

**Comment by osdeverr** [comment]
@j123123, все ещё жду

**Comment by j123123** [comment]
@osdeverr чего ты там ждешь?

**Comment by j123123** [comment]
@osdeverr ты хочешь, чтобы я тебе как-нибудь навредил? Ну давай я опишу тебе коротко ситуацию.

На хабре (где ты уже read-only) указана твоя дата рождения - 30 октября 2004. Сейчас 10 августа, 2017 год. В соответствии с этими данными, тебе должно быть на данный момент 12 лет.

Окей, смотрим сюда https://help.github.com/articles/github-terms-of-service/#b-account-terms

> You must be age 13 or older. While we are thrilled to see brilliant young coders get excited by learning to program, we must comply with United States law. GitHub does not target our Service to children under 13, and we do not permit any Users under 13 on our Service. If we learn of any User under the age of 13, we will terminate that User’s account immediately. If you are a resident of a country outside the United States, your country’s minimum age may be older; in such a case, you are responsible for complying with your country’s laws.

13 лет тебе еще нет, так что твой аккаунт могут попросту заблокировать, если написать жалобу на тебя.

Так что ты давай подожди до 30 октября 2017 года, а пока что давай потише в этой ситуации, братишка :trollface:

**Comment by osdeverr** [comment]
нуок(9( просто интересовался

**Comment by osdeverr** [comment]
шобы тебя не злить и не мешать мне, предлагаю забыть друг о друге

**Comment by j123123** [comment]
@osdeverr Во-первых, я на тебя не злюсь(и никогда не злился), мне на тебя совершенно пофиг. Во-вторых я о тебе даже успел забыть, но ты зачем-то решил о себе напомнить. У меня вообще полно других дел. Вот лучше зацени, какую хуиту в исходниках самсугна пишут http://www.govnokod.ru/23227

Да, и в-третьих есть намного более интересные и долбанутые школьники. Например вот зацени, антивирусы какие-то https://arhivach.org/thread/177623/ https://huita.org/posts/2280 https://youtu.be/RxVwNMy8WDM/watch?v=RxVwNMy8WDM

Всякие там поповы, бабушкины, куранины, откуда такое ненормальное желание выебнуться и типа сказать "смотрите я вундеркинд-гений, в 12 лет пишу свою ОС с нуля, антивирус с нуля, и вообще...". Потом еще кого-то там ддосить, кому-то что-то пытаться доказать, ну что за бред? Хотя ты ж школьник, что с тебя взять...

В общем удачи тебе и всего хорошего. Учись в школе хорошо, не пиши на C++ и прочих говноязыках. И лисп еще освой, хороший язык, там **ГОМОИКОННОСТЬ**

**Comment by osdeverr** [comment]
антивирусы знаю) если честно, то в 2015 я был малолетним долбоебом, щас и ось уже перестал писать
