### ISSUE TITLE
После залогинивания говнокод не открывается

### ISSUE THREAD

**Issue by j123123** [wiistriker/govnokod.ru#38]
При попытке зайти под моим логином j123123, говнокод перестает работать и выдает ошибку 504 Gateway Time-out

**Comment by j123123** [comment]
Иногда удаление кукисов исправляет ситуацию для меня, иногда не исправляет (если не исправляет, сайт перестает работать у всех после моей попытки зайти на него). В случае, если удаление кукисов исправляет ситуацию, последующая попытка логина в говнокод с правильным паролем опять все ломает, сайт не открывается.

**Comment by j123123** [comment]
Да, воспроизводится. При попытке залогинивания на говнокод, сайт начинает выдавать 504 Gateway Time-out ошибку не только для меня, но и вообще: http://downforeveryoneorjustme.com/http://govnokod.ru/
@wiistriker

**Comment by wiistriker** [comment]
fixed
