### ISSUE TITLE
Разминусовать старые говнокоды.

### ISSUE THREAD

**Issue by guestinho** [wiistriker/govnokod.ru#48]
Раз уж голосование отключено, можно сбросить рейтинг всех говнокодов?
Много годноты утоплено ботами-минусаторами. Целые разделы были скрыты.
И дать кому-нибудь права на удаление/скрытые, если попадается спам.

**Comment by COWuTEJIbTBOEuMAMKu** [comment]
На хуй сам пойдёшь или тебе особое приглашение нужно?

**Comment by guestinho** [comment]
Приглашения, **COWuTEJIbTBOEuMAMKu**

**Comment by wiistriker** [comment]
У меня есть информация по всем голосам, я просто откачу их все назад и рейтинги вернутся
