### ISSUE TITLE
Вопросы по поднятию проекта на локалхосте

### ISSUE THREAD

**Issue by guestinho** [wiistriker/govnokod.ru#52]
1) Вроде бы поднялось, но css-ки и js-ки недоступны из веба
`<link rel="stylesheet" type="text/css" href="/css/compiled/main_style_1.css" />`
по такому пути ничего нету
их как-то нужно отдельно компилить?

2) Я использую xampp. Как-то можно запускать стандартным способом, а не через 
`php app/console server:run --docroot=www/`
?

**Comment by wiistriker** [comment]
php app/console assets:dump

**Comment by guestinho** [comment]
Да я уже понял, что этот проект ещё в сыром состоянии, и нет смысла пробовать запускать. Лучше ответьте на вопрос в legacy https://github.com/wiistriker/govnokod_legacy/issues/2

**Comment by wiistriker** [comment]
Этот проект уже нормально собирается и запускается. Лучше заниматься им, чтобы обновленная версия вышла как можно раньше
