### ISSUE TITLE
Сайт заблокирован Роскомнадзором 

### ISSUE THREAD

**Issue by guestinho** [wiistriker/govnokod.ru#53]
Возможные причины:
- пропаганда запрещённых в РФ организаций на главной странице 
- пропаганда педофилии, насилия, и гомосексуализма на главной странице и в комментариях

**Comment by wiistriker** [comment]
Всё проще - забанили подсеть digitalicean

**Comment by wiistriker** [comment]
Подключил cloudflare, получше должно быть
