### ISSUE TITLE
"CSRF verification error" после перехода на CloudFlare

### ISSUE THREAD

**Issue by guestinho** [wiistriker/govnokod.ru#56]
При отправке комментов и постов.
Пофикси! Задолбало уже!

Также отключи ненужный "[email protected]".

**Comment by wiistriker** [comment]
А в чем проблема? Всё работает вроде?

Какой еще email protected?

**Comment by wiistriker** [comment]
Что-то иногда проявляется, иногда нет. В чем соль? Cloudflare как-то кеширует или что?

**Comment by wiistriker** [comment]
Проверь сейчас, отключил кеширование на cf

**Comment by guestinho** [comment]
> Какой еще email protected?

Открой HTML страницы http://govnokod.ru/22444
Там поищи "protected]", который скриптом на клиенте заменяется.
Нахер это нужно?

**Comment by guestinho** [comment]
@wiistriker ping
CSRF verification error всё ещё не пофиксился.

**Comment by wiistriker** [comment]
@guestinho как повторить? у меня не повторяется

**Comment by Skinpack** [comment]
@wiistriker 
1. Зайти на http://govnokod.ru/24681#comment427777 ;
2. Нажать кнопку "Ответить", написать комментарий, кнопку "Отправить" не нажимать;
3. Подождать 1 минуту или больше;
4. Нажать "Отправить";
5. Ошибка компиляции комментария: csrf verification error.

Появляется достаточно часто, если не появляется — нужно перезагрузить страницу со сбросом кэша и повторить алгоритм с пункта 2.

**Comment by wiistriker** [comment]
fixed

**Comment by guestinho** [comment]
@wiistriker Не пофиксилось
